In [25]:
from src.models.modulated_siren import ModulatedSirenModel
import torch

In [26]:
s = ModulatedSirenModel()

Model initialized
Layer 1: SirenLayer(
  (linear): Linear(in_features=2, out_features=16, bias=True)
)
Layer 2: SirenLayer(
  (linear): Linear(in_features=16, out_features=3, bias=True)
)
Bias: Parameter containing:
tensor([-0.0653, -0.1203,  0.1965,  0.2199, -0.5381, -0.5614,  0.3566,  0.3372,
        -0.0931, -0.0901,  0.3083,  0.6350,  0.3718,  0.3416, -0.4769,  0.2205],
       requires_grad=True)
Bias_len: 16
Bias shape: torch.Size([16])


In [27]:
from PIL import Image

image_path = '/Users/arkadipiven/Documents/Code/functa/rendered/chair/0bc2011018e2463ca119ebce4e15a94b/000.png'
image = Image.open(image_path).convert("RGB")

In [28]:
print(image.size)

(512, 512)


In [29]:
import numpy as np

image_array = np.array(image)
print(image_array.shape)

(512, 512, 3)


In [30]:
image_rgb = image.convert("RGB")

In [31]:
image_array = np.array(image_rgb)
print(image_array.shape)

(512, 512, 3)


In [32]:
print(image_array[0][0])

[0 0 0]


In [33]:
from src.datasets.chairs import Chairs

cd = Chairs("/Users/arkadipiven/Documents/Code/functa/rendered/chair")

Chairs dataset initialized


In [51]:
chair_1, chair_2 = cd[5]

x = np.arange(512)
y = np.arange(512)
xx, yy = np.meshgrid(x, y)

coordinates = np.stack([xx, yy], axis=-1)
coordinates_tensor = torch.tensor(coordinates, dtype=torch.float32).unsqueeze(0)
coordinates_tensor = coordinates_tensor.reshape(-1, 2)
print(coordinates_tensor.shape)
print(coordinates_tensor)

y_hat = s(coordinates_tensor)
print(y_hat)
loss = torch.nn.functional.mse_loss(y_hat, chair_1.reshape(-1, 3))
loss

# s.forward(chair_1)

torch.Size([262144, 2])
tensor([[  0.,   0.],
        [  1.,   0.],
        [  2.,   0.],
        ...,
        [509., 511.],
        [510., 511.],
        [511., 511.]])
tensor([[ 0.6025,  0.9461,  0.2877],
        [-0.2260,  0.7866,  0.5828],
        [ 0.4106,  0.9479, -0.5832],
        ...,
        [-0.0316,  0.4697,  0.1416],
        [ 0.3046,  0.9991,  0.7341],
        [-0.1286,  0.6190,  0.9047]], grad_fn=<SinBackward0>)


tensor(2690.5525, grad_fn=<MseLossBackward0>)

In [22]:
print(cd[1500])

IndexError: list index out of range