In [1]:
from src.models.siren import SirenModel

In [2]:
s = SirenModel()

Model initialized
Layer 1: SirenLayer(
  (linear): Linear(in_features=2, out_features=256, bias=True)
)
Bias: Parameter containing:
tensor([-0.6700, -0.1606, -0.0025,  0.2536,  0.4526, -0.2029, -0.6334,  0.0269,
         0.3145, -0.1252,  0.5901,  0.6595,  0.0737,  0.6985,  0.5844,  0.4448,
        -0.3322,  0.4990, -0.4167,  0.5975,  0.2644, -0.2256,  0.4710,  0.5414,
        -0.3834, -0.5285,  0.5031, -0.3842, -0.6362, -0.6607, -0.0436,  0.1803,
         0.0487,  0.2676, -0.0853,  0.2975,  0.5851, -0.0794, -0.4763, -0.3932,
         0.0259, -0.2987,  0.4753, -0.1617, -0.4156,  0.4891,  0.3292,  0.2525,
         0.4246, -0.2091, -0.4607,  0.3130, -0.3174, -0.6131,  0.0764,  0.3652,
        -0.6608, -0.0151,  0.5764,  0.3922, -0.3396, -0.2735, -0.6380,  0.5625,
         0.0098, -0.1009, -0.2450,  0.3814, -0.3004, -0.2152,  0.1548, -0.4019,
         0.5282, -0.3840, -0.6009,  0.3372, -0.5890, -0.1842,  0.5263, -0.6743,
        -0.0366, -0.1508,  0.5917,  0.6003, -0.4640, -0.3274,  0.473

In [3]:
from PIL import Image

image_path = '/Users/arkadipiven/Documents/Code/functa/rendered/chair/0bc2011018e2463ca119ebce4e15a94b/000.png'
image = Image.open(image_path).convert("RGB")
image.show()

In [4]:
print(image.size)

(512, 512)


In [5]:
import numpy as np

image_array = np.array(image)
print(image_array.shape)

(512, 512, 3)


In [6]:
image_rgb = image.convert("RGB")

In [7]:
image_array = np.array(image_rgb)
print(image_array.shape)

(512, 512, 3)


In [8]:
print(image_array[0][0])

[0 0 0]


In [9]:
from src.datasets.chairs import Chairs

cd = Chairs("/Users/arkadipiven/Documents/Code/functa/rendered/chair")

Chairs dataset initialized


In [10]:
print(cd[1000])

(array([0, 0, 0], dtype=uint8), array([0, 0, 0], dtype=uint8), 488, 1)


In [19]:
print(cd[1500])

(array([1, 1, 1], dtype=uint8), array([1, 1, 1], dtype=uint8), 476, 2)
